# Procedurally generates fact-quiz chains for the Drive Co-Pilot pool, one
# pool per interest tag. Each FACTS entry is a single multiple-choice item;
# the generator assembles them into 6-step chains with deterministic seeds.
#
# Each chain row gets a unique flavor phrase in its intro so chains stay
# distinguishable at the DB layer even when fact-sets overlap.
#
# Fact entry shape:
#   { q: "stem after 'Which is …?'", a: "correct option", d: ["3 distractors"], f: "fun fact" }
module TopicTriviaGenerator
  FLAVORS = %w[
    Lightning Quick Sunrise Sunset Lakeside Mountain Riverside Harbor
    Maple Pinecrest Oakgrove Birchwood Cedarpoint Willowdale Brookside Foxglove
    Lavender Saffron Indigo Crimson Emerald Sapphire Amber Ivory
    Compass Lantern Beacon Anchor Comet Meteor Aurora Horizon
    Quill Tome Atlas Sage Hearth Lark Falcon Heron
  ].freeze

  FACTS = {
    "animals" => [
      { q: "the fastest land animal", a: "Cheetah", d: %w[Lion Horse Greyhound], f: "Cheetahs hit 70 mph in short bursts." },
      { q: "the largest animal alive today", a: "Blue whale", d: [ "African elephant", "Giraffe", "Polar bear" ], f: "Blue whales can reach over 100 feet long." },
      { q: "the only mammal capable of true flight", a: "Bat", d: %w[Squirrel Possum Sugar-glider], f: "Other 'flying' mammals only glide between trees." },
      { q: "the tallest land animal", a: "Giraffe", d: %w[Elephant Camel Moose], f: "Adult giraffes can be 18 feet tall." },
      { q: "the most poisonous frog", a: "Golden poison frog", d: [ "Cane toad", "Bullfrog", "Tree frog" ], f: "A single golden poison frog has enough toxin for 10 people." },
      { q: "an animal with three hearts", a: "Octopus", d: %w[Squid Crab Lobster], f: "Two hearts pump blood through its gills; one through its body." },
      { q: "the largest fish in the ocean", a: "Whale shark", d: [ "Great white shark", "Manta ray", "Marlin" ], f: "Whale sharks can be 40 feet long but eat plankton." },
      { q: "a marsupial that carries its baby in a pouch", a: "Kangaroo", d: %w[Beaver Otter Hedgehog], f: "Baby kangaroos are called joeys." },
      { q: "a baby kangaroo called", a: "Joey", d: %w[Cub Kit Pup], f: "Joeys live in the pouch for several months." },
      { q: "the group spiders belong to", a: "Arachnids", d: %w[Insects Crustaceans Reptiles], f: "Arachnids have 8 legs; insects have 6." },
      { q: "the largest big cat", a: "Tiger", d: %w[Lion Jaguar Leopard], f: "Siberian tigers can weigh over 600 pounds." },
      { q: "an animal that changes color", a: "Chameleon", d: %w[Iguana Toad Skink], f: "Chameleons shift color for mood and temperature regulation, not just camouflage." },
      { q: "the loudest animal on Earth", a: "Sperm whale", d: %w[Howler-monkey Elephant Lion], f: "Sperm whales' clicks can reach 230 decibels underwater." },
      { q: "an egg-laying mammal", a: "Platypus", d: %w[Otter Beaver Hedgehog], f: "Platypuses and echidnas are the only mammals that lay eggs." },
      { q: "the longest-living animal on Earth", a: "Ocean quahog clam", d: %w[Galápagos-tortoise Bowhead-whale Greenland-shark], f: "One quahog clam was estimated at 507 years old." },
      { q: "the largest bird that cannot fly", a: "Ostrich", d: %w[Emu Cassowary Penguin], f: "Ostriches can run up to 45 mph instead." },
      { q: "the smallest bird in the world", a: "Bee hummingbird", d: %w[Wren Goldcrest Bushtit], f: "Bee hummingbirds weigh less than a penny." },
      { q: "the longest snake species", a: "Reticulated python", d: %w[Anaconda King-cobra Boa-constrictor], f: "Reticulated pythons can exceed 25 feet." },
      { q: "the only big cat that lives in groups (called prides)", a: "Lion", d: %w[Tiger Leopard Cheetah], f: "Lion prides usually have related females and their cubs." },
      { q: "the world's slowest mammal", a: "Sloth", d: %w[Manatee Koala Panda], f: "Sloths move about 0.15 mph on the ground." },
      { q: "a primate famous for its silvery-white face and large eyes", a: "Lemur", d: %w[Gibbon Marmoset Tarsier], f: "Lemurs live almost exclusively on Madagascar." },
      { q: "a flightless bird from Antarctica", a: "Penguin", d: %w[Puffin Albatross Tern], f: "Emperor penguins can dive over 1,500 feet deep." },
      { q: "the world's largest rodent", a: "Capybara", d: %w[Beaver Porcupine Groundhog], f: "Capybaras can weigh over 140 pounds." },
      { q: "an apex predator of the Arctic", a: "Polar bear", d: %w[Wolverine Snow-leopard Arctic-fox], f: "Polar bears have black skin under their white fur." },
      { q: "an amphibian that breathes through its skin", a: "Frog", d: %w[Lizard Salamander Crocodile], f: "Frogs use both lungs and their moist skin to take in oxygen." },
      { q: "the animal said to have the strongest bite of any living creature", a: "Saltwater crocodile", d: %w[Hyena Hippo Great-white-shark], f: "Their bite force can exceed 3,700 PSI." },
      { q: "a mammal that uses echolocation underwater", a: "Dolphin", d: %w[Seal Walrus Sea-otter], f: "Dolphins send clicks and listen for the echoes to 'see' in the dark." },
      { q: "the world's largest land predator", a: "Polar bear", d: %w[Grizzly-bear Lion Tiger], f: "Adult males can weigh over 1,300 pounds." }
    ],
    "science" => [
      { q: "the gas plants take in for photosynthesis", a: "Carbon dioxide", d: %w[Oxygen Nitrogen Helium], f: "Plants release oxygen back into the air as a byproduct." },
      { q: "the chemical formula for water", a: "H₂O", d: %w[CO₂ NaCl O₂], f: "Two hydrogen atoms bonded to one oxygen." },
      { q: "the hardest natural substance", a: "Diamond", d: %w[Steel Granite Iron], f: "Diamonds form deep underground over a billion years." },
      { q: "the largest organ of the human body by surface area", a: "Skin", d: %w[Liver Lungs Intestine], f: "Adult skin covers about 2 square meters." },
      { q: "the speed of light (rounded)", a: "300,000 km/s", d: [ "3,000 km/s", "30,000 km/s", "3,000,000 km/s" ], f: "Light travels Earth-to-Moon in about 1.3 seconds." },
      { q: "the smallest unit of matter that retains an element's properties", a: "Atom", d: %w[Molecule Cell Quark], f: "Atoms have a nucleus surrounded by electrons." },
      { q: "the gas that makes up most of Earth's atmosphere", a: "Nitrogen", d: %w[Oxygen Argon Carbon-dioxide], f: "About 78% of air is nitrogen." },
      { q: "the part of a cell that contains DNA", a: "Nucleus", d: %w[Mitochondrion Ribosome Cytoplasm], f: "The nucleus directs the cell's activities." },
      { q: "the force that holds us to the Earth", a: "Gravity", d: %w[Magnetism Friction Inertia], f: "Gravity also keeps the Moon in orbit around Earth." },
      { q: "the process by which liquid becomes gas", a: "Evaporation", d: %w[Condensation Sublimation Melting], f: "Evaporation cools you as sweat evaporates from your skin." },
      { q: "the boiling point of water at sea level (Celsius)", a: "100°C", d: %w[80°C 90°C 110°C], f: "At higher altitudes water boils at lower temperatures." },
      { q: "the freezing point of water (Celsius)", a: "0°C", d: %w[-10°C 10°C 32°C], f: "0°C and 32°F mark the same temperature." },
      { q: "an element with the symbol Au", a: "Gold", d: %w[Silver Aluminum Argon], f: "Au comes from the Latin word for gold, aurum." },
      { q: "the brightest planet seen from Earth", a: "Venus", d: %w[Mars Jupiter Mercury], f: "Venus is sometimes called the Morning Star or Evening Star." },
      { q: "an example of a renewable energy source", a: "Solar", d: %w[Coal Oil Natural-gas], f: "Solar panels turn sunlight directly into electricity." },
      { q: "the part of an atom that has a positive charge", a: "Proton", d: %w[Electron Neutron Quark], f: "Protons live in the nucleus alongside neutrons." },
      { q: "the process where plants make food from sunlight", a: "Photosynthesis", d: %w[Respiration Germination Transpiration], f: "Plants combine CO₂ + water + sunlight → sugar + oxygen." },
      { q: "the unit of electrical resistance", a: "Ohm", d: %w[Volt Watt Ampere], f: "Resistance is measured in ohms (Ω)." },
      { q: "the closest star to Earth (other than the Sun)", a: "Proxima Centauri", d: %w[Polaris Sirius Alpha-Centauri-A], f: "Light from Proxima Centauri takes about 4.2 years to reach us." },
      { q: "the layer of Earth we live on", a: "Crust", d: %w[Mantle Outer-core Inner-core], f: "The crust is just 5–70 km thick depending on location." },
      { q: "the term for animals that eat only plants", a: "Herbivore", d: %w[Carnivore Omnivore Insectivore], f: "Cows, deer, and elephants are all herbivores." },
      { q: "the device used to measure earthquakes", a: "Seismograph", d: %w[Barometer Thermometer Hygrometer], f: "Seismographs trace ground motion onto a chart or sensor." },
      { q: "the most abundant gas in the Sun", a: "Hydrogen", d: %w[Helium Oxygen Carbon], f: "The Sun fuses hydrogen into helium in its core." },
      { q: "the number of planets in our solar system", a: "8", d: %w[7 9 10], f: "Pluto was reclassified as a dwarf planet in 2006." },
      { q: "the part of the human body that pumps blood", a: "Heart", d: %w[Lungs Liver Brain], f: "An adult heart beats about 100,000 times a day." },
      { q: "the basic unit of life", a: "Cell", d: %w[Atom Tissue Organ], f: "Most cells are too small to see without a microscope." },
      { q: "the SI unit of force", a: "Newton", d: %w[Joule Pascal Watt], f: "Named for Sir Isaac Newton." }
    ],
    "history" => [
      { q: "the year World War II ended", a: "1945", d: %w[1939 1942 1948], f: "Japan surrendered in September 1945." },
      { q: "the first US president", a: "George Washington", d: [ "Thomas Jefferson", "Abraham Lincoln", "John Adams" ], f: "Sworn in on April 30, 1789." },
      { q: "the year humans first landed on the Moon", a: "1969", d: %w[1959 1965 1972], f: "Apollo 11 touched down July 20, 1969." },
      { q: "the civilization that built Machu Picchu", a: "Inca", d: %w[Aztec Maya Olmec], f: "Built around 1450 high in the Peruvian Andes." },
      { q: "the wall that fell in 1989", a: "Berlin Wall", d: [ "Great Wall of China", "Hadrian's Wall", "Wall of Jericho" ], f: "Berlin had been divided for 28 years." },
      { q: "the year the Titanic sank", a: "1912", d: %w[1898 1905 1920], f: "It struck an iceberg on its maiden voyage." },
      { q: "the ancient wonder still standing today", a: "Great Pyramid of Giza", d: [ "Colossus of Rhodes", "Hanging Gardens of Babylon", "Lighthouse of Alexandria" ], f: "Built around 2560 BC for Pharaoh Khufu." },
      { q: "the country that gifted the Statue of Liberty to the US", a: "France", d: %w[Spain Italy England], f: "It was a gift to mark 100 years of American independence." },
      { q: "the year the Declaration of Independence was signed", a: "1776", d: %w[1750 1789 1812], f: "July 4, 1776 — the founding of the United States." },
      { q: "the dynasty that built the Great Wall of China's most famous sections", a: "Ming", d: %w[Han Tang Qing], f: "The Ming rebuilt and extended large sections in the 1300s–1600s." },
      { q: "the explorer who reached the Americas in 1492", a: "Christopher Columbus", d: [ "Ferdinand Magellan", "Vasco da Gama", "Marco Polo" ], f: "Columbus made four voyages between 1492 and 1502." },
      { q: "the political event of 1991 that ended the Soviet Union", a: "Dissolution of the USSR", d: [ "October Revolution", "Russian Civil War", "Cuban Missile Crisis" ], f: "The USSR split into 15 independent countries." },
      { q: "the war fought between the North and South in the US (1861–1865)", a: "American Civil War", d: [ "American Revolution", "War of 1812", "Mexican-American War" ], f: "It led to the abolition of slavery in the United States." },
      { q: "the queen who reigned over the United Kingdom from 1952 to 2022", a: "Elizabeth II", d: [ "Victoria", "Elizabeth I", "Anne" ], f: "Her 70-year reign was the longest in British history." },
      { q: "the year of the French Revolution's start", a: "1789", d: %w[1750 1776 1804], f: "It began with the storming of the Bastille on July 14, 1789." },
      { q: "the man who first reached the South Pole (1911)", a: "Roald Amundsen", d: [ "Robert Falcon Scott", "Ernest Shackleton", "James Cook" ], f: "Amundsen's team beat Scott's by 33 days." },
      { q: "the ship that brought Pilgrims to Plymouth in 1620", a: "Mayflower", d: %w[Santa-María Endeavour Beagle], f: "About 102 passengers sailed on the Mayflower." },
      { q: "the year the Berlin Wall was built", a: "1961", d: %w[1945 1955 1972], f: "It went up overnight on August 13, 1961." },
      { q: "the Egyptian pharaoh whose tomb was found in 1922", a: "Tutankhamun", d: %w[Ramesses-II Khufu Cleopatra], f: "Howard Carter discovered the tomb nearly intact." },
      { q: "the leader of India's nonviolent independence movement", a: "Mahatma Gandhi", d: [ "Jawaharlal Nehru", "Sardar Patel", "B.R. Ambedkar" ], f: "Gandhi led the Salt March in 1930." },
      { q: "the German chancellor who started World War II", a: "Adolf Hitler", d: %w[Bismarck Kaiser-Wilhelm Goebbels], f: "Germany invaded Poland in September 1939." },
      { q: "the era of mass European migration to the Americas (1880s–1920s)", a: "Age of Mass Migration", d: [ "Renaissance", "Enlightenment", "Industrial Revolution" ], f: "Over 25 million people came to the US in this period." },
      { q: "the empire ruled by Genghis Khan", a: "Mongol Empire", d: [ "Roman Empire", "Ottoman Empire", "Persian Empire" ], f: "At its peak, the Mongol Empire was the largest contiguous land empire in history." },
      { q: "the document signed at Runnymede in 1215 limiting royal power", a: "Magna Carta", d: [ "Bill of Rights", "Magna Vita", "Declaration of Rights" ], f: "King John of England signed it under pressure from his barons." },
      { q: "the year the United Nations was founded", a: "1945", d: %w[1939 1948 1955], f: "It replaced the League of Nations after WWII." },
      { q: "the war between the US and the Soviet Union (without direct fighting)", a: "Cold War", d: [ "Vietnam War", "Korean War", "Gulf War" ], f: "It lasted roughly from 1947 to 1991." }
    ],
    "space" => [
      { q: "the closest star to Earth", a: "The Sun", d: %w[Polaris Proxima-Centauri Sirius], f: "Sunlight reaches Earth in about 8 minutes." },
      { q: "the planet famous for its rings", a: "Saturn", d: %w[Mars Jupiter Neptune], f: "Saturn's rings are mostly ice and rock chunks." },
      { q: "the galaxy we live in", a: "Milky Way", d: %w[Andromeda Whirlpool Sombrero], f: "The Milky Way holds 100–400 billion stars." },
      { q: "the first person on the Moon", a: "Neil Armstrong", d: [ "Buzz Aldrin", "Yuri Gagarin", "John Glenn" ], f: "He stepped down on July 20, 1969." },
      { q: "the largest planet in our solar system", a: "Jupiter", d: %w[Earth Saturn Uranus], f: "Over 1,300 Earths could fit inside Jupiter." },
      { q: "the smallest planet in our solar system", a: "Mercury", d: %w[Mars Pluto Venus], f: "Mercury is only slightly larger than our Moon." },
      { q: "the 'Red Planet'", a: "Mars", d: %w[Jupiter Venus Saturn], f: "Iron oxide (rust) gives Mars its color." },
      { q: "the hottest planet in our solar system", a: "Venus", d: %w[Mercury Mars Jupiter], f: "Its thick atmosphere traps heat — surface ~465°C." },
      { q: "the first satellite ever launched into orbit", a: "Sputnik 1", d: %w[Vanguard Explorer-1 Luna-1], f: "The USSR launched Sputnik on October 4, 1957." },
      { q: "the dwarf planet beyond Neptune", a: "Pluto", d: %w[Eris Ceres Haumea], f: "Pluto was reclassified as a dwarf planet in 2006." },
      { q: "the name of NASA's first crewed Moon program", a: "Apollo", d: %w[Mercury Gemini Artemis], f: "Apollo 11 was the first to land humans on the Moon." },
      { q: "the natural satellite of Earth", a: "The Moon", d: %w[Io Titan Phobos], f: "The Moon is about 238,000 miles away." },
      { q: "the part of the Sun we see", a: "Photosphere", d: %w[Corona Chromosphere Core], f: "The photosphere is the visible 'surface' at ~5,500°C." },
      { q: "a region of space with gravity so strong nothing can escape", a: "Black hole", d: %w[Neutron-star Pulsar Quasar], f: "Even light can't escape past a black hole's event horizon." },
      { q: "the asteroid belt's location", a: "Between Mars and Jupiter", d: [ "Between Earth and Mars", "Beyond Neptune", "Between Saturn and Uranus" ], f: "It contains millions of rocky bodies left from the early solar system." },
      { q: "the largest moon in our solar system", a: "Ganymede", d: %w[Titan Callisto Europa], f: "Ganymede orbits Jupiter and is bigger than Mercury." },
      { q: "the comet that returns roughly every 76 years", a: "Halley's Comet", d: [ "Hale-Bopp", "Comet NEOWISE", "Encke" ], f: "Halley's next return is expected in 2061." },
      { q: "the planet with the fastest winds", a: "Neptune", d: %w[Jupiter Saturn Uranus], f: "Neptune's winds can exceed 1,500 mph." },
      { q: "the telescope launched in 1990 that orbits Earth", a: "Hubble Space Telescope", d: %w[James-Webb Spitzer Chandra], f: "Hubble has produced over a million observations." },
      { q: "the planet tilted on its side", a: "Uranus", d: %w[Neptune Saturn Mars], f: "Uranus's axis is tilted about 98° to its orbit." },
      { q: "the part of the Moon always facing Earth", a: "Near side", d: %w[Far-side South-pole North-pole], f: "Tidal locking means we only ever see one face of the Moon." },
      { q: "the constellation containing the Big Dipper", a: "Ursa Major", d: %w[Orion Cassiopeia Leo], f: "'Ursa Major' means 'Great Bear' in Latin." },
      { q: "the unit astronomers use for distances within the solar system", a: "Astronomical Unit", d: %w[Light-year Parsec Megameter], f: "1 AU is Earth-Sun distance: about 93 million miles." },
      { q: "the type of star our Sun is", a: "Yellow dwarf", d: %w[Red-giant White-dwarf Blue-supergiant], f: "It's about halfway through its ~10-billion-year main-sequence life." },
      { q: "the first private company to send astronauts to the ISS", a: "SpaceX", d: %w[Blue-Origin Boeing Virgin-Galactic], f: "SpaceX's Crew Dragon docked at the ISS in May 2020." }
    ],
    "geography" => [
      { q: "the largest desert on Earth", a: "Antarctic Desert", d: %w[Sahara Gobi Arabian], f: "Antarctica gets very little precipitation, making it a desert." },
      { q: "the longest river in the world", a: "Nile", d: %w[Amazon Yangtze Mississippi], f: "The Nile flows over 4,100 miles through Africa." },
      { q: "the largest ocean", a: "Pacific Ocean", d: %w[Atlantic Indian Arctic], f: "It covers about a third of Earth's surface." },
      { q: "the highest mountain on Earth", a: "Mount Everest", d: %w[K2 Kangchenjunga Denali], f: "Everest peaks at 29,032 feet (8,849 m)." },
      { q: "the country with the largest population", a: "India", d: [ "United States", "China", "Indonesia" ], f: "India overtook China around 2023." },
      { q: "the continent with the most countries", a: "Africa", d: %w[Asia Europe South-America], f: "Africa has 54 internationally recognized countries." },
      { q: "the smallest country in the world", a: "Vatican City", d: %w[Monaco Nauru San-Marino], f: "Vatican City is about 0.49 square kilometers." },
      { q: "the country that has the most islands", a: "Sweden", d: %w[Indonesia Philippines Norway], f: "Sweden has over 220,000 islands, most uninhabited." },
      { q: "the longest mountain range on land", a: "Andes", d: %w[Himalayas Rockies Alps], f: "The Andes run about 4,300 miles along South America's west coast." },
      { q: "the largest lake by area", a: "Caspian Sea", d: [ "Lake Superior", "Lake Victoria", "Lake Baikal" ], f: "Despite the name, the Caspian Sea is a giant landlocked lake." },
      { q: "the deepest lake in the world", a: "Lake Baikal", d: [ "Caspian Sea", "Lake Tanganyika", "Lake Superior" ], f: "Baikal reaches over 5,300 feet deep." },
      { q: "the country that contains the Sahara's largest area", a: "Algeria", d: %w[Egypt Libya Sudan], f: "Algeria is the largest country in Africa by area." },
      { q: "the capital of Australia", a: "Canberra", d: %w[Sydney Melbourne Perth], f: "Canberra was chosen as a compromise between rival cities Sydney and Melbourne." },
      { q: "the capital of Canada", a: "Ottawa", d: %w[Toronto Montreal Vancouver], f: "Ottawa sits on the border of Ontario and Quebec." },
      { q: "the capital of Brazil", a: "Brasília", d: [ "Rio de Janeiro", "São Paulo", "Salvador" ], f: "Brasília was purpose-built and became capital in 1960." },
      { q: "the river that flows through Egypt", a: "Nile", d: %w[Tigris Euphrates Congo], f: "Ancient Egyptian civilization thrived along the Nile." },
      { q: "the country known as the Land of the Rising Sun", a: "Japan", d: [ "China", "Korea", "Vietnam" ], f: "Japan's name in Japanese (Nihon) means 'origin of the sun'." },
      { q: "the country containing both the Sahara and the Sahel", a: "Niger", d: %w[Algeria Mali Chad], f: "Niger straddles the Sahara desert to the north and Sahel to the south." },
      { q: "the country home to the Amazon rainforest's largest area", a: "Brazil", d: %w[Peru Colombia Venezuela], f: "About 60% of the Amazon is in Brazil." },
      { q: "the country with the most time zones", a: "France", d: [ "Russia", "United States", "China" ], f: "France has 12 time zones counting its overseas territories." },
      { q: "the body of water between Britain and continental Europe", a: "English Channel", d: [ "North Sea", "Irish Sea", "Bay of Biscay" ], f: "The Chunnel runs beneath it, connecting England and France." },
      { q: "the country that borders both China and Russia (longest border with both)", a: "Mongolia", d: [ "North Korea", "Kazakhstan", "India" ], f: "Mongolia is landlocked between Russia and China." },
      { q: "the continent Antarctica is closest to", a: "South America", d: %w[Africa Australia Asia], f: "The Drake Passage separates Antarctica from the tip of South America." },
      { q: "the only country that's also a continent", a: "Australia", d: %w[Greenland Russia Canada], f: "Australia covers the smallest continent, all as one country." },
      { q: "the strait between Spain and Morocco", a: "Strait of Gibraltar", d: [ "Strait of Hormuz", "Bering Strait", "Bosphorus" ], f: "Gibraltar connects the Atlantic to the Mediterranean." }
    ],
    "sports" => [
      { q: "the number of players on a soccer team on the field", a: "11", d: %w[9 10 12], f: "11 including the goalkeeper." },
      { q: "the points scored for a touchdown in NFL football", a: "6", d: %w[3 7 10], f: "Plus 1 for the extra-point kick, totaling 7." },
      { q: "the number of holes in a standard round of golf", a: "18", d: %w[9 12 24], f: "Standardized at St Andrews in Scotland." },
      { q: "the city of the first modern Olympics in 1896", a: "Athens", d: %w[Paris London Rome], f: "Greece, home of the original ancient Olympics." },
      { q: "the number of players per side on a basketball team during play", a: "5", d: %w[4 6 7], f: "Total of 10 on the court for both teams." },
      { q: "the sport played at Wimbledon", a: "Tennis", d: %w[Cricket Rugby Polo], f: "Wimbledon is the oldest tennis tournament, dating from 1877." },
      { q: "the country that invented baseball-like sports first played in (modern game)", a: "United States", d: %w[England Cuba Japan], f: "Baseball took its modern form in the US in the 1800s." },
      { q: "the trophy awarded to the NHL champion", a: "Stanley Cup", d: [ "Vince Lombardi Trophy", "Larry O'Brien Trophy", "Commissioner's Trophy" ], f: "Donated in 1892 by Lord Stanley of Preston." },
      { q: "the sport featuring a 'try' and a 'scrum'", a: "Rugby", d: %w[Cricket Soccer Lacrosse], f: "A try scores 5 points in rugby union." },
      { q: "the bicycle race held mostly in France each summer", a: "Tour de France", d: [ "Giro d'Italia", "Vuelta a España", "Paris-Roubaix" ], f: "First held in 1903; the leader wears a yellow jersey." },
      { q: "the swimmer with the most Olympic gold medals", a: "Michael Phelps", d: [ "Mark Spitz", "Ian Thorpe", "Caeleb Dressel" ], f: "Phelps has 23 Olympic gold medals." },
      { q: "the team sport played on horseback with mallets", a: "Polo", d: %w[Cricket Croquet Lacrosse], f: "Polo dates back over 2,000 years in Persia." },
      { q: "the sport of fencing's three weapons", a: "Foil, épée, sabre", d: [ "Foil, dagger, rapier", "Sabre, kris, katana", "Foil, broadsword, kris" ], f: "Each weapon has different target areas." },
      { q: "the city that hosted the 2020 Summer Olympics (held in 2021)", a: "Tokyo", d: %w[Rio Beijing Paris], f: "Postponed from 2020 due to the pandemic." },
      { q: "the tennis grand slam played on clay", a: "French Open", d: [ "Wimbledon", "Australian Open", "US Open" ], f: "Roland Garros is played on red clay courts in Paris." },
      { q: "the number of innings in a standard MLB game", a: "9", d: %w[7 10 12], f: "Extra innings continue until a winner is decided." },
      { q: "the player who broke the 4-minute mile in 1954", a: "Roger Bannister", d: [ "Jim Ryun", "Hicham El Guerrouj", "Steve Cram" ], f: "Bannister ran 3:59.4 on May 6, 1954." },
      { q: "the sport with a 'butterfly' stroke", a: "Swimming", d: %w[Rowing Diving Surfing], f: "Butterfly was added to the Olympics in 1956." },
      { q: "the championship for European club soccer's top teams", a: "Champions League", d: [ "Europa League", "FA Cup", "Copa America" ], f: "UEFA Champions League's anthem is famous worldwide." },
      { q: "the country that won the first FIFA World Cup (1930)", a: "Uruguay", d: %w[Argentina Brazil Italy], f: "Uruguay also hosted the inaugural tournament." },
      { q: "the number of points for a 3-pointer in basketball", a: "3", d: %w[2 4 5], f: "The 3-point line was introduced to the NBA in 1979–80." },
      { q: "the field events that involve throwing", a: "Shot put", d: %w[High-jump Long-jump Hurdles], f: "Throwing events also include discus, hammer, and javelin." },
      { q: "the team sport originally played by Indigenous peoples of North America", a: "Lacrosse", d: %w[Hockey Baseball Soccer], f: "Lacrosse is Canada's national summer sport." },
      { q: "the most-played sport in the world by participants", a: "Soccer", d: %w[Cricket Basketball Volleyball], f: "Estimated over 250 million players globally." },
      { q: "the 'Triple Crown' in US horse racing", a: "Kentucky Derby, Preakness, Belmont", d: [ "Derby, Oaks, St. Leger", "Derby, Arc, Breeders' Cup", "Preakness, Belmont, Travers" ], f: "Only 13 horses have won all three races." }
    ],
    "music" => [
      { q: "the number of strings on a standard guitar", a: "6", d: %w[4 8 12], f: "12-string guitars exist for a fuller sound." },
      { q: "the highest-pitched of these string instruments", a: "Violin", d: %w[Cello Double-bass Viola], f: "Violins are tuned an octave above violas." },
      { q: "the number of keys on a standard piano", a: "88", d: %w[66 76 96], f: "52 white keys and 36 black keys." },
      { q: "the Beatle known as 'the Quiet One'", a: "George Harrison", d: [ "John Lennon", "Paul McCartney", "Ringo Starr" ], f: "He wrote 'Here Comes the Sun' and 'Something'." },
      { q: "the family that includes drums and cymbals", a: "Percussion", d: %w[Strings Woodwinds Brass], f: "Percussion is anything you hit, shake, or scrape." },
      { q: "what 'forte' means in music", a: "Loudly", d: %w[Slowly Quietly Smoothly], f: "Forte (f) instructs the musician to play loud." },
      { q: "the composer of the Ninth Symphony with the 'Ode to Joy'", a: "Ludwig van Beethoven", d: %w[Mozart Bach Brahms], f: "Beethoven composed his 9th while almost completely deaf." },
      { q: "the four-stringed instrument plucked in country and bluegrass music", a: "Banjo", d: %w[Mandolin Ukulele Sitar], f: "Five-string banjos are most common in bluegrass." },
      { q: "the band behind 'Bohemian Rhapsody'", a: "Queen", d: [ "The Beatles", "Led Zeppelin", "The Rolling Stones" ], f: "Freddie Mercury was the band's lead vocalist." },
      { q: "the country where the tango originated", a: "Argentina", d: %w[Spain Brazil Cuba], f: "Tango developed in Buenos Aires in the late 1800s." },
      { q: "the Italian word for 'fast' on a musical score", a: "Allegro", d: %w[Adagio Andante Largo], f: "Allegro usually means cheerfully and quickly." },
      { q: "the musical symbol shaped like an ampersand at the start of a staff", a: "Treble clef", d: %w[Bass-clef Alto-clef Tenor-clef], f: "Treble clef is also called the G clef." },
      { q: "the singer of 'Like a Rolling Stone' and a 2016 Nobel laureate", a: "Bob Dylan", d: [ "Bruce Springsteen", "Paul Simon", "Leonard Cohen" ], f: "He won the Nobel Prize in Literature in 2016." },
      { q: "the keyboard instrument with pipes", a: "Organ", d: %w[Piano Harpsichord Accordion], f: "Pipe organs can have thousands of pipes." },
      { q: "the conductor's stick", a: "Baton", d: %w[Bow Mallet Tuner], f: "Conductors use a baton to keep time and shape the music." },
      { q: "the home country of K-pop", a: "South Korea", d: %w[Japan China Thailand], f: "BTS, Blackpink, and other groups have made K-pop a global force." },
      { q: "the song often sung at the start of a US baseball game", a: "The Star-Spangled Banner", d: [ "America the Beautiful", "My Country, 'Tis of Thee", "God Bless America" ], f: "It became the US national anthem in 1931." },
      { q: "the Austrian-born child prodigy composer who died in 1791", a: "Wolfgang Amadeus Mozart", d: %w[Beethoven Schubert Haydn], f: "Mozart wrote his first symphony around age 8." },
      { q: "the genre of music originating in 1970s New York with rapping and DJing", a: "Hip-hop", d: %w[Disco Funk Reggae], f: "Hip-hop began in the Bronx in the early 1970s." },
      { q: "the instrument played by a 'percussionist using sticks'", a: "Drums", d: %w[Piano Violin Guitar], f: "A drum kit usually has a snare, bass drum, and cymbals." },
      { q: "the term for music sung without instruments", a: "A cappella", d: %w[Solo Duet Aria], f: "From Italian for 'in the manner of the chapel'." },
      { q: "the saxophone family — soprano, alto, tenor, ___", a: "Baritone", d: %w[Soprano Bass Contralto], f: "The four main sizes are soprano, alto, tenor, and baritone." },
      { q: "the lead singer of Nirvana", a: "Kurt Cobain", d: [ "Dave Grohl", "Eddie Vedder", "Chris Cornell" ], f: "Nirvana's 1991 album 'Nevermind' defined grunge." },
      { q: "the British band fronted by Mick Jagger", a: "The Rolling Stones", d: [ "The Who", "The Kinks", "The Beatles" ], f: "The Stones formed in London in 1962." },
      { q: "the Italian word for 'soft' in music", a: "Piano", d: %w[Forte Mezzo Vivace], f: "Confusingly, 'piano' also names the instrument." }
    ],
    "movies" => [
      { q: "the very first Best Picture Oscar winner (1929)", a: "Wings", d: [ "Casablanca", "Gone with the Wind", "Citizen Kane" ], f: "A silent film about WWI fighter pilots." },
      { q: "the director of Jurassic Park and E.T.", a: "Steven Spielberg", d: [ "George Lucas", "James Cameron", "Quentin Tarantino" ], f: "Spielberg practically defined the summer blockbuster." },
      { q: "the wizarding school in the Harry Potter series", a: "Hogwarts", d: [ "Beauxbatons", "Durmstrang", "Ilvermorny" ], f: "Hogwarts has four houses sorted by personality." },
      { q: "what CGI stands for", a: "Computer Generated Imagery", d: [ "Cinematic Graphic Illusion", "Color Gradient Index", "Camera Guided Imaging" ], f: "Used for digital effects and characters." },
      { q: "the 1997 film about an ocean liner that sinks", a: "Titanic", d: %w[Avatar Inception Gladiator], f: "Titanic won 11 Oscars." },
      { q: "the studio behind Toy Story", a: "Pixar", d: %w[DreamWorks Disney Ghibli], f: "Toy Story (1995) was the first fully CGI feature film." },
      { q: "the director of The Godfather", a: "Francis Ford Coppola", d: [ "Martin Scorsese", "Stanley Kubrick", "Brian De Palma" ], f: "Coppola also made Apocalypse Now." },
      { q: "the highest-grossing film of all time (2024)", a: "Avatar", d: %w[Avengers:Endgame Titanic Star-Wars:The-Force-Awakens], f: "Avatar reclaimed the spot after a 2022 re-release." },
      { q: "the studio behind Star Wars (original)", a: "Lucasfilm", d: %w[20th-Century-Fox Disney Universal], f: "Disney acquired Lucasfilm in 2012." },
      { q: "the film starring Marlon Brando as Don Corleone", a: "The Godfather", d: [ "Goodfellas", "Scarface", "Casino" ], f: "Brando won Best Actor but declined to accept the Oscar." },
      { q: "the 1939 film with Dorothy and the Wizard", a: "The Wizard of Oz", d: [ "Gone with the Wind", "Mary Poppins", "It's a Wonderful Life" ], f: "Judy Garland was 16 when she played Dorothy." },
      { q: "the Coen Brothers film that won Best Picture in 2008", a: "No Country for Old Men", d: %w[Fargo Burn-After-Reading Inside-Llewyn-Davis], f: "Based on the Cormac McCarthy novel." },
      { q: "the director of Pulp Fiction", a: "Quentin Tarantino", d: [ "Martin Scorsese", "Spike Lee", "Paul Thomas Anderson" ], f: "Tarantino is known for non-linear storytelling and dialogue." },
      { q: "the actor who played Indiana Jones", a: "Harrison Ford", d: [ "Tom Hanks", "Mel Gibson", "Bruce Willis" ], f: "Ford also played Han Solo and Rick Deckard." },
      { q: "the film featuring a great white shark on Amity Island", a: "Jaws", d: [ "Free Willy", "Deep Blue Sea", "The Meg" ], f: "Spielberg's 1975 hit helped invent the summer blockbuster." },
      { q: "the 'Hobbit-sized' fictional homeland of Frodo Baggins", a: "The Shire", d: %w[Mordor Rohan Gondor], f: "The Shire is in J.R.R. Tolkien's Middle-earth." },
      { q: "the Marvel hero who wields a hammer named Mjolnir", a: "Thor", d: %w[Hulk Loki Odin], f: "Only the worthy can lift Mjolnir." },
      { q: "the actor who played Hannibal Lecter in 'Silence of the Lambs'", a: "Anthony Hopkins", d: [ "Robert De Niro", "Al Pacino", "Gary Oldman" ], f: "Hopkins won Best Actor with under 25 minutes of screen time." },
      { q: "the studio behind Spirited Away", a: "Studio Ghibli", d: %w[Pixar Toho Madhouse], f: "Founded by Hayao Miyazaki and Isao Takahata in 1985." },
      { q: "the actor who played Forrest Gump", a: "Tom Hanks", d: [ "Kevin Bacon", "Bill Murray", "Robin Williams" ], f: "Hanks won the Best Actor Oscar for the role." },
      { q: "the studio behind the original Toy Story", a: "Pixar", d: %w[Disney DreamWorks Blue-Sky], f: "Toy Story took four years to make." },
      { q: "the movie featuring Tony Stark as Iron Man", a: "Iron Man", d: %w[The-Avengers Iron-Patriot Captain-America], f: "The 2008 film launched the Marvel Cinematic Universe." },
      { q: "the movie about a group seeking the One Ring", a: "The Lord of the Rings", d: %w[The-Hobbit Game-of-Thrones Eragon], f: "Peter Jackson's trilogy was filmed entirely in New Zealand." },
      { q: "the director famous for thrillers like Psycho and The Birds", a: "Alfred Hitchcock", d: [ "Orson Welles", "Stanley Kubrick", "Akira Kurosawa" ], f: "Hitchcock is called the 'Master of Suspense'." },
      { q: "the film that opens with 'A long time ago in a galaxy far, far away…'", a: "Star Wars", d: %w[Star-Trek Stargate Battlestar-Galactica], f: "Originally just 'Star Wars'; later subtitled 'A New Hope'." }
    ],
    "movies_kids" => [
      { q: "what Buzz Lightyear says", a: "To infinity and beyond", d: [ "Hakuna matata", "Yabba dabba doo", "May the Force be with you" ], f: "Buzz believes he's a real space ranger." },
      { q: "the kind of animal Simba is in The Lion King", a: "Lion", d: %w[Tiger Cheetah Leopard], f: "Simba even means 'lion' in Swahili." },
      { q: "the Disney princess with a pet tiger named Rajah", a: "Jasmine", d: %w[Belle Mulan Moana], f: "Jasmine is from Aladdin." },
      { q: "the snowman in Frozen", a: "Olaf", d: %w[Sven Marshmallow Hans], f: "Olaf loves summer (even though it would melt him)." },
      { q: "the type of fish Nemo is", a: "Clownfish", d: %w[Tuna Salmon Marlin], f: "Clownfish live among sea anemones for protection." },
      { q: "the film about dragons on the island of Berk", a: "How to Train Your Dragon", d: [ "Brave", "Tangled", "Encanto" ], f: "Hiccup tames a Night Fury named Toothless." },
      { q: "the film featuring Po, a kung fu panda", a: "Kung Fu Panda", d: %w[Madagascar Shrek Bolt], f: "Po becomes the chosen Dragon Warrior." },
      { q: "the toy cowboy in Toy Story", a: "Woody", d: %w[Buzz Jessie Stinky-Pete], f: "Woody is owned by Andy." },
      { q: "the film featuring the song 'Let It Go'", a: "Frozen", d: %w[Moana Tangled Encanto], f: "The song won the 2014 Academy Award for Best Original Song." },
      { q: "the movie with a robot named WALL-E", a: "WALL-E", d: %w[Big-Hero-6 The-Iron-Giant Robots], f: "WALL-E spends 700 years cleaning Earth alone." },
      { q: "the movie about a young lion exiled from his pride", a: "The Lion King", d: %w[Madagascar Brother-Bear Tarzan], f: "Simba returns to challenge his uncle Scar." },
      { q: "the rat who dreams of cooking in Paris", a: "Remy", d: %w[Stuart-Little Despereaux Splinter], f: "He stars in Pixar's Ratatouille." },
      { q: "the orange fish on a quest to find his son", a: "Marlin", d: %w[Dory Nemo Gill], f: "Marlin crosses the Pacific to find Nemo." },
      { q: "the green ogre who lives in a swamp", a: "Shrek", d: %w[Mike-Wazowski Sully Po], f: "Shrek's best friend is Donkey." },
      { q: "the princess who has long magical hair", a: "Rapunzel", d: %w[Cinderella Snow-White Anna], f: "Her hair glows when she sings." },
      { q: "the film about emotions inside a girl's head", a: "Inside Out", d: %w[Soul Up Coco], f: "Joy, Sadness, Anger, Fear, and Disgust live in Riley's mind." },
      { q: "the film featuring a young boy and his pet dragon Toothless", a: "How to Train Your Dragon", d: %w[Pete's-Dragon Sleeping-Beauty Brave], f: "Hiccup and Toothless become best friends." },
      { q: "the song-and-dance lemur king in Madagascar", a: "King Julien", d: %w[Mort Maurice Alex], f: "Julien rules Madagascar's lemurs with flair." },
      { q: "the Disney film about a young Chinese warrior", a: "Mulan", d: %w[Pocahontas Brave Moana], f: "Mulan disguises herself as a man to take her father's place in the army." },
      { q: "the Pixar film about an old man, a boy, and a flying house", a: "Up", d: %w[Coco Onward Soul], f: "Carl uses thousands of balloons to fly his house to South America." },
      { q: "the film about a Polynesian princess who sets sail", a: "Moana", d: %w[Brave Encanto Pocahontas], f: "Moana voyages with the demigod Maui." },
      { q: "the toy story villain who teaches at the daycare", a: "Lotso", d: %w[Stinky-Pete Sid Zurg], f: "Lots-o'-Huggin' Bear is in Toy Story 3." },
      { q: "the kingdom Anna and Elsa rule", a: "Arendelle", d: %w[Corona Atlantica DunBroch], f: "Arendelle is loosely inspired by Norway." },
      { q: "the bug movie featuring an ant named Flik", a: "A Bug's Life", d: %w[Antz Bee-Movie Ant-Man], f: "Pixar's second feature film, from 1998." },
      { q: "the heroic chef in Pixar's Ratatouille", a: "Linguini", d: %w[Skinner Anton-Ego Colette], f: "With Remy's help, Linguini becomes a famous chef." }
    ],
    "dinosaurs" => [
      { q: "the dinosaur whose name means 'tyrant lizard king'", a: "T. rex", d: %w[Velociraptor Stegosaurus Brachiosaurus], f: "Full name: Tyrannosaurus rex." },
      { q: "the dinosaur with three horns and a frill", a: "Triceratops", d: %w[Stegosaurus Ankylosaurus Iguanodon], f: "Two long brow horns and a short nose horn." },
      { q: "the dinosaur with bony plates running down its back", a: "Stegosaurus", d: %w[Triceratops Velociraptor Diplodocus], f: "Plates may have helped regulate body temperature." },
      { q: "a long-necked plant-eating dinosaur", a: "Brachiosaurus", d: %w[Allosaurus Compsognathus Spinosaurus], f: "Brachiosaurus could reach treetops 30+ feet up." },
      { q: "roughly how long ago non-avian dinosaurs went extinct", a: "66 million years", d: [ "6,000 years", "6 million years", "660 million years" ], f: "An asteroid impact 66 million years ago likely caused it." },
      { q: "the modern descendants of dinosaurs", a: "Birds", d: %w[Lizards Crocodiles Snakes], f: "Birds evolved from small theropod dinosaurs." },
      { q: "the era when dinosaurs lived", a: "Mesozoic", d: %w[Paleozoic Cenozoic Precambrian], f: "Mesozoic ran from about 252 to 66 million years ago." },
      { q: "the time period when T. rex lived (late ___ period)", a: "Cretaceous", d: %w[Jurassic Triassic Permian], f: "T. rex stomped around 68–66 million years ago." },
      { q: "the small, swift, intelligent predator featured in Jurassic Park", a: "Velociraptor", d: %w[Compsognathus Dilophosaurus Gallimimus], f: "Real Velociraptors were turkey-sized and feathered." },
      { q: "the term for plant-eating dinosaurs", a: "Herbivores", d: %w[Carnivores Omnivores Insectivores], f: "Diplodocus and Brachiosaurus are classic herbivorous dinosaurs." },
      { q: "the dinosaur with a thick, club-shaped tail used as a weapon", a: "Ankylosaurus", d: %w[Stegosaurus Iguanodon Parasaurolophus], f: "Ankylosaurus' tail club could break bones." },
      { q: "the duck-billed dinosaur known for its head crest", a: "Parasaurolophus", d: %w[Hadrosaurus Lambeosaurus Edmontosaurus], f: "Its crest may have been used to make loud calls." },
      { q: "the gigantic semi-aquatic predator with a sail on its back", a: "Spinosaurus", d: %w[Allosaurus Carnotaurus Giganotosaurus], f: "Spinosaurus may have been larger than T. rex." },
      { q: "a dinosaur fossil's preserved hard parts are most often", a: "Bones", d: %w[Feathers Skin Brains], f: "Soft tissue rarely fossilizes." },
      { q: "the era right after the dinosaur extinction", a: "Cenozoic", d: %w[Mesozoic Paleozoic Holocene], f: "Mammals diversified rapidly in the Cenozoic." },
      { q: "the scientist who studies dinosaurs and other ancient life", a: "Paleontologist", d: %w[Geologist Archaeologist Anthropologist], f: "Paleontologists study fossils to understand prehistoric life." },
      { q: "the giant marine reptile (NOT a dinosaur) with paddle-like flippers", a: "Plesiosaur", d: %w[Apatosaurus T.-rex Allosaurus], f: "Plesiosaurs swam the seas during the dinosaur era." },
      { q: "the flying reptile (NOT a dinosaur) with wing membranes", a: "Pterosaur", d: %w[Archaeopteryx Velociraptor Compsognathus], f: "Pterosaurs include Pteranodon and Quetzalcoatlus." },
      { q: "the earliest known feathered dinosaur-like animal", a: "Archaeopteryx", d: %w[Velociraptor Compsognathus Microraptor], f: "Archaeopteryx had teeth, claws on wings, and a bony tail — but also feathers." },
      { q: "the dinosaur named for its long whip-like tail", a: "Diplodocus", d: %w[Brachiosaurus Apatosaurus Mamenchisaurus], f: "Diplodocus could grow up to 90 feet long." },
      { q: "the country with abundant Mongolian dinosaur fossil sites", a: "Mongolia", d: %w[China Argentina USA], f: "The Gobi Desert has yielded famous finds like Velociraptor and Oviraptor." },
      { q: "the type of dinosaur Triceratops belonged to", a: "Ceratopsian", d: %w[Theropod Sauropod Ankylosaur], f: "Ceratopsians are horned dinosaurs." },
      { q: "the dinosaur with the longest neck", a: "Mamenchisaurus", d: %w[Diplodocus Brachiosaurus Apatosaurus], f: "Mamenchisaurus' neck could be over 30 feet long alone." },
      { q: "the supercontinent that existed when dinosaurs first appeared", a: "Pangaea", d: %w[Gondwana Laurasia Rodinia], f: "Pangaea began breaking up during the Mesozoic." },
      { q: "the small, bird-like dinosaur that may have brooded its eggs", a: "Oviraptor", d: %w[Velociraptor Microraptor Compsognathus], f: "Its name means 'egg thief' — though it likely sat on its own eggs." }
    ],
    "cars" => [
      { q: "what 'EV' stands for", a: "Electric Vehicle", d: [ "Extra Vehicle", "Engine Variant", "Express Van" ], f: "EVs run on batteries instead of fuel." },
      { q: "the company that makes the Mustang", a: "Ford", d: %w[Chevrolet Dodge Toyota], f: "Ford launched the Mustang in 1964." },
      { q: "the company famous for Model S and Model 3 EVs", a: "Tesla", d: %w[Rivian Lucid Polestar], f: "Tesla was founded in 2003." },
      { q: "what ABS stands for in car brakes", a: "Anti-lock Braking System", d: [ "Active Brake System", "Automatic Brake Switch", "Axle Brake Set" ], f: "ABS prevents wheels from locking under hard braking." },
      { q: "what MPG measures", a: "Fuel efficiency", d: [ "Top speed", "Engine size", "Trunk capacity" ], f: "Miles per gallon — higher MPG = farther per gallon." },
      { q: "the Japanese maker of the Civic and Accord", a: "Honda", d: %w[Toyota Nissan Mazda], f: "Honda also makes motorcycles and lawn mowers." },
      { q: "the German maker of the 911", a: "Porsche", d: %w[BMW Audi Mercedes-Benz], f: "The Porsche 911 has been in production since 1963." },
      { q: "the Italian luxury sports car brand with a prancing horse logo", a: "Ferrari", d: %w[Lamborghini Maserati Pagani], f: "Ferrari was founded by Enzo Ferrari in 1939." },
      { q: "the British luxury maker famous for Phantom and Ghost", a: "Rolls-Royce", d: %w[Bentley Jaguar Aston-Martin], f: "Rolls-Royce dates from 1904." },
      { q: "the type of fuel used in most modern diesel engines", a: "Diesel", d: %w[Gasoline Ethanol Propane], f: "Diesel engines use compression-ignition instead of spark plugs." },
      { q: "the company that makes the Wrangler", a: "Jeep", d: %w[Ford Chevrolet Dodge], f: "Jeep originated from WWII military vehicles." },
      { q: "the city of the world's largest auto show (NAIAS)", a: "Detroit", d: [ "Los Angeles", "Geneva", "Frankfurt" ], f: "Detroit is sometimes called Motor City." },
      { q: "the engine layout with cylinders in two rows forming a V", a: "V engine", d: [ "Inline engine", "Boxer engine", "Rotary engine" ], f: "V6 and V8 are common V-engine setups." },
      { q: "the part that powers an EV", a: "Battery pack", d: [ "Fuel tank", "Catalytic converter", "Carburetor" ], f: "Most EVs use lithium-ion battery packs." },
      { q: "the safety device that inflates on collision", a: "Airbag", d: %w[Seatbelt Bumper Crumple-zone], f: "Most modern cars have multiple airbags, including side curtains." },
      { q: "the system that translates engine power to the wheels", a: "Transmission", d: %w[Differential Driveshaft Axle], f: "Transmissions can be manual or automatic." },
      { q: "the German company that owns Audi, Porsche, and Lamborghini", a: "Volkswagen Group", d: [ "BMW Group", "Daimler", "Stellantis" ], f: "Volkswagen also owns SEAT, Skoda, and Bentley." },
      { q: "the iconic VW vehicle with a curved roof and rear-mounted engine", a: "Beetle", d: %w[Golf Passat Polo], f: "Over 21 million original Beetles were produced." },
      { q: "the Korean company that makes the Sonata and Tucson", a: "Hyundai", d: %w[Kia Daewoo Ssangyong], f: "Hyundai's name means 'modernity' in Korean." },
      { q: "the Japanese maker of the Land Cruiser", a: "Toyota", d: %w[Nissan Honda Mitsubishi], f: "Toyota became the world's largest automaker by volume." },
      { q: "the part that mixes air and fuel in older cars", a: "Carburetor", d: %w[Alternator Spark-plug Radiator], f: "Most modern cars use fuel injection instead." },
      { q: "the famous American open-top sports car", a: "Chevrolet Corvette", d: [ "Ford GT", "Dodge Viper", "Pontiac Solstice" ], f: "Chevrolet has built Corvettes continuously since 1953." },
      { q: "the country where Volvo originated", a: "Sweden", d: %w[Germany Denmark Finland], f: "Volvo (Latin for 'I roll') was founded in Gothenburg in 1927." },
      { q: "the famous race held in Le Mans, France", a: "24 Hours of Le Mans", d: [ "Indy 500", "Monaco Grand Prix", "Daytona 500" ], f: "Teams race nonstop for 24 hours on the same circuit." },
      { q: "the racing series with cars covering only single-seater open-wheel formats", a: "Formula 1", d: %w[NASCAR Rally Drag-racing], f: "F1 is the top international single-seater championship." }
    ],
    "video_games" => [
      { q: "Mario's brother", a: "Luigi", d: %w[Wario Toad Yoshi], f: "Luigi wears green and is a bit taller than Mario." },
      { q: "the series where players catch creatures", a: "Pokémon", d: %w[Zelda Mario Minecraft], f: "Pokémon launched in 1996 in Japan." },
      { q: "the green-clad hero of The Legend of Zelda", a: "Link", d: %w[Mario Zelda Ganondorf], f: "Zelda is the princess; Link is the player character." },
      { q: "the game where players build worlds from blocks", a: "Minecraft", d: %w[Terraria Roblox Fortnite], f: "Minecraft launched in 2009 and is the best-selling game ever." },
      { q: "the color of Sonic the Hedgehog", a: "Blue", d: %w[Red Green Yellow], f: "Sonic became Sega's mascot in 1991." },
      { q: "what 'NPC' stands for", a: "Non-Player Character", d: [ "New Player Character", "Network Pixel Code", "Next Player Cue" ], f: "NPCs are controlled by the game, not the player." },
      { q: "the game series featuring the master chief in green armor", a: "Halo", d: %w[Doom Destiny Gears-of-War], f: "Halo helped launch the original Xbox in 2001." },
      { q: "the puzzle game where you rotate falling blocks", a: "Tetris", d: %w[Bejeweled Candy-Crush Puyo-Puyo], f: "Tetris was created in 1984 by Alexey Pajitnov." },
      { q: "the racing series featuring go-karts and bananas", a: "Mario Kart", d: [ "Need for Speed", "Forza", "Gran Turismo" ], f: "Mario Kart 64 introduced 4-player split-screen racing." },
      { q: "the open-world game series with Geralt the witcher", a: "The Witcher", d: %w[Skyrim Dragon-Age Mass-Effect], f: "Based on a Polish fantasy novel series." },
      { q: "the survival game with FPS mode set in a battle royale", a: "Fortnite", d: %w[PUBG Apex-Legends Warzone], f: "Fortnite Battle Royale launched in 2017." },
      { q: "the game where you play as a plumber jumping on goombas", a: "Super Mario Bros.", d: [ "Donkey Kong", "Sonic the Hedgehog", "Mega Man" ], f: "Super Mario Bros. launched on the NES in 1985." },
      { q: "the company that makes the PlayStation", a: "Sony", d: %w[Microsoft Nintendo Sega], f: "The PlayStation launched in 1994." },
      { q: "the company that makes the Xbox", a: "Microsoft", d: %w[Sony Nintendo Sega], f: "The original Xbox launched in 2001." },
      { q: "the country where Nintendo originated", a: "Japan", d: [ "South Korea", "United States", "Taiwan" ], f: "Nintendo started in 1889 making playing cards in Kyoto." },
      { q: "the iconic yellow ghost-eating game", a: "Pac-Man", d: [ "Donkey Kong", "Q*bert", "Galaga" ], f: "Pac-Man debuted in arcades in 1980." },
      { q: "the open-world Western game by Rockstar", a: "Red Dead Redemption", d: [ "Grand Theft Auto", "Call of Juarez", "Wild West Online" ], f: "Red Dead Redemption 2 launched in 2018." },
      { q: "the studio behind Half-Life and Portal", a: "Valve", d: %w[Bethesda Bungie id-Software], f: "Valve also runs the Steam game store." },
      { q: "the elf protagonist of the Elder Scrolls V: Skyrim", a: "Dragonborn", d: %w[Geralt Aragorn Link], f: "The Dragonborn can absorb dragon souls to learn shouts." },
      { q: "the game with farms, Junimos, and a Pelican Town setting", a: "Stardew Valley", d: %w[Harvest-Moon Animal-Crossing Story-of-Seasons], f: "Made by a single developer, ConcernedApe." },
      { q: "the cooperative cooking-chaos game", a: "Overcooked", d: %w[Cooking-Mama Burger-Time Diner-Dash], f: "Players must coordinate to serve dishes on time." },
      { q: "the game where players solve puzzles with a portal gun", a: "Portal", d: %w[Half-Life Antichamber Talos-Principle], f: "Portal's antagonist is the AI GLaDOS." },
      { q: "the open-world Japanese RPG with the hero Cloud Strife", a: "Final Fantasy VII", d: [ "Final Fantasy X", "Chrono Trigger", "Dragon Quest XI" ], f: "Originally released for the PlayStation in 1997." },
      { q: "the controller buttons on a SNES include A, B, X, and ___", a: "Y", d: %w[Z C R], f: "SNES introduced the four-face-button layout." },
      { q: "the multiplayer team shooter with classes like Soldier and Medic", a: "Team Fortress 2", d: %w[Overwatch Apex-Legends Counter-Strike], f: "Valve's TF2 has been free-to-play since 2011." }
    ],
    "disney" => [
      { q: "Mickey Mouse's longtime girlfriend", a: "Minnie", d: %w[Daisy Clarabelle Pluto], f: "Mickey and Minnie both debuted in 'Steamboat Willie' (1928)." },
      { q: "Mickey's pet dog", a: "Pluto", d: %w[Goofy Donald Daisy], f: "Pluto is the only main character in Mickey's gang who doesn't talk." },
      { q: "Elsa's sister in Frozen", a: "Anna", d: %w[Aurora Ariel Belle], f: "Anna is the younger, more outgoing sister." },
      { q: "the kind of creature Stitch is", a: "Alien", d: %w[Dog Koala Hamster], f: "Stitch is Experiment 626 from another planet." },
      { q: "the bird in Moana", a: "Rooster", d: %w[Parrot Pelican Albatross], f: "Hei Hei is a not-so-bright rooster." },
      { q: "the Disney park in Orlando, Florida", a: "Walt Disney World", d: %w[Disneyland Disneyland-Paris Tokyo-Disney], f: "Walt Disney World opened in 1971." },
      { q: "the original Disneyland's city", a: "Anaheim", d: %w[Burbank Tokyo Orlando], f: "Disneyland opened in 1955 in Anaheim, California." },
      { q: "the princess with seven dwarves", a: "Snow White", d: %w[Cinderella Aurora Rapunzel], f: "Snow White is Disney's first feature-length animated heroine." },
      { q: "the princess who loses a glass slipper at the ball", a: "Cinderella", d: %w[Aurora Belle Snow-White], f: "Cinderella's slipper helps the prince find her again." },
      { q: "the magic carpet's owner in Aladdin", a: "Aladdin", d: %w[Genie Jafar Abu], f: "The carpet is sentient and very expressive." },
      { q: "the dog who falls in love with a cocker spaniel", a: "Tramp", d: %w[Pongo Dodger Buddy], f: "Lady and the Tramp share spaghetti and meatballs." },
      { q: "the lost-boys' leader's clock-eating crocodile", a: "Tick-Tock", d: %w[Croco Sneer Snappy], f: "Tick-Tock the Crocodile haunts Captain Hook in Peter Pan." },
      { q: "the witch in Snow White", a: "The Evil Queen", d: %w[Maleficent Ursula Cruella], f: "She transforms into a creepy peddler to deliver the poisoned apple." },
      { q: "the dragon Maleficent transforms into", a: "Dragon", d: %w[Phoenix Hydra Wyvern], f: "She breathes green fire in Sleeping Beauty." },
      { q: "the kingdom from Frozen", a: "Arendelle", d: %w[Corona DunBroch Atlantica], f: "Arendelle is loosely based on Norway." },
      { q: "the song in Frozen sung by Elsa atop the mountain", a: "Let It Go", d: [ "Do You Want to Build a Snowman?", "Into the Unknown", "Show Yourself" ], f: "Idina Menzel performed the original Broadway-style ballad." },
      { q: "the Italian Disney film about a wooden boy", a: "Pinocchio", d: %w[Geppetto Bambi Dumbo], f: "Pinocchio (1940) was Disney's second feature." },
      { q: "the animated film featuring a Native American princess", a: "Pocahontas", d: %w[Mulan Brave Moana], f: "Released in 1995, with the song 'Colors of the Wind'." },
      { q: "the king of the seas in The Little Mermaid", a: "King Triton", d: %w[Poseidon Neptune Davy-Jones], f: "Triton is Ariel's father in The Little Mermaid." },
      { q: "the friendly genie voiced by Robin Williams", a: "Genie", d: %w[Iago Abu Sultan], f: "Genie offers Aladdin three wishes." },
      { q: "the prince beast in Beauty and the Beast", a: "Beast", d: %w[Phillip Eric Charming], f: "He's cursed to remain a beast until he learns to love." },
      { q: "the deer prince whose mother is killed in his Disney film", a: "Bambi", d: %w[Thumper Flower Faline], f: "Bambi is a white-tailed deer in the original 1942 film." },
      { q: "the protagonist of Wreck-It Ralph", a: "Ralph", d: [ "Fix-It Felix", "Vanellope", "Calhoun" ], f: "Ralph is the 'bad guy' in an arcade game who wants to be a hero." },
      { q: "Disney's Polynesian seafaring teenager", a: "Moana", d: %w[Mulan Pocahontas Anna], f: "Moana voyages with the demigod Maui." },
      { q: "the cheerful Andean adventurer who collects souls in Coco", a: "Miguel", d: %w[Hector Ernesto Imelda], f: "Coco celebrates Día de los Muertos." }
    ],
    "superhero" => [
      { q: "Spider-Man's real name", a: "Peter Parker", d: [ "Bruce Wayne", "Tony Stark", "Steve Rogers" ], f: "Bitten by a radioactive spider as a teenager." },
      { q: "the planet Superman is from", a: "Krypton", d: %w[Asgard Tamaran Oa], f: "Superman's Kryptonian name is Kal-El." },
      { q: "Iron Man's real name", a: "Tony Stark", d: [ "Steve Rogers", "Bruce Banner", "Thor Odinson" ], f: "Tony Stark is a billionaire inventor." },
      { q: "what Captain America's shield is made of (in the comics)", a: "Vibranium", d: %w[Adamantium Titanium Steel], f: "Vibranium absorbs vibrations and impacts." },
      { q: "the green hero who emerges when Bruce Banner gets angry", a: "Hulk", d: %w[Thor Hawkeye Ant-Man], f: "Banner becomes the Hulk after a gamma-radiation accident." },
      { q: "the team including Iron Man, Cap, Thor, and Hulk", a: "Avengers", d: [ "X-Men", "Justice League", "Fantastic Four" ], f: "The Avengers debuted in Marvel comics in 1963." },
      { q: "Bruce Wayne's superhero identity", a: "Batman", d: %w[Robin Nightwing Green-Arrow], f: "Batman protects Gotham City." },
      { q: "the team of mutants led by Professor X", a: "X-Men", d: [ "Avengers", "Justice League", "Fantastic Four" ], f: "Professor X's school in Westchester trains young mutants." },
      { q: "the city Batman protects", a: "Gotham", d: %w[Metropolis Star-City Coast-City], f: "Gotham is a dark, gothic city plagued by crime." },
      { q: "the city Superman protects", a: "Metropolis", d: %w[Gotham Coast-City Star-City], f: "Metropolis is a bright, optimistic counterpart to Gotham." },
      { q: "the speedster from DC Comics", a: "The Flash", d: %w[Quicksilver Sonic Speedy], f: "Barry Allen is the most well-known Flash." },
      { q: "the Norse god hero played by Chris Hemsworth", a: "Thor", d: %w[Loki Odin Heimdall], f: "Thor's hammer is named Mjolnir." },
      { q: "the green-skinned bald antagonist of the Avengers in 'Infinity War'", a: "Thanos", d: %w[Ultron Loki Killmonger], f: "Thanos seeks the Infinity Stones." },
      { q: "Diana Prince's superhero identity", a: "Wonder Woman", d: %w[Supergirl Catwoman Black-Widow], f: "She's an Amazonian princess from Themyscira." },
      { q: "the merman king of Atlantis", a: "Aquaman", d: %w[Namor Triton Submariner], f: "Aquaman commands the seas in DC Comics." },
      { q: "the team of four with the powers of fire, stretch, invisibility, and stone", a: "Fantastic Four", d: [ "X-Men", "Justice League", "Inhumans" ], f: "The team gained powers after a cosmic-radiation accident." },
      { q: "the mutant with adamantium claws and a healing factor", a: "Wolverine", d: %w[Cyclops Beast Sabretooth], f: "Wolverine's real name is Logan." },
      { q: "the African nation Black Panther rules", a: "Wakanda", d: %w[Genosha Latveria Sokovia], f: "Wakanda is the world's most technologically advanced nation in Marvel." },
      { q: "the friend who often supports Spider-Man (also editor of the Daily Bugle)", a: "J. Jonah Jameson", d: [ "Aunt May", "Mary Jane", "Norman Osborn" ], f: "Jameson is convinced Spider-Man is a menace." },
      { q: "the alien symbiote that bonds with Eddie Brock", a: "Venom", d: %w[Carnage Anti-Venom Toxin], f: "Venom is a Spider-Man villain turned antihero." },
      { q: "the Marvel hero who can shrink to insect size", a: "Ant-Man", d: %w[Wasp Spider-Man Beast], f: "Scott Lang and Hank Pym have both worn the suit." },
      { q: "the supervillain known as the Clown Prince of Crime", a: "Joker", d: [ "Riddler", "Penguin", "Two-Face" ], f: "Joker is Batman's archenemy." },
      { q: "the mutant who can manipulate the weather", a: "Storm", d: %w[Jean-Grey Mystique Rogue], f: "Ororo Munroe is a key X-Men member." },
      { q: "the deadly mercenary in red and black with a healing factor", a: "Deadpool", d: %w[Wolverine Punisher Cable], f: "Deadpool breaks the fourth wall constantly." },
      { q: "the half-Atlantean king who reigns over the underwater Marvel kingdom", a: "Namor", d: %w[Aquaman Triton Triton], f: "Namor is one of Marvel's oldest characters, dating from 1939." }
    ],
    "food" => [
      { q: "the main ingredient in guacamole", a: "Avocado", d: %w[Tomato Onion Lime], f: "Botanically, avocados are a berry." },
      { q: "the country that invented pizza", a: "Italy", d: %w[USA Greece France], f: "Modern pizza comes from Naples." },
      { q: "the country where sushi originated", a: "Japan", d: %w[China Korea Thailand], f: "Sushi pairs vinegared rice with raw or cooked seafood." },
      { q: "the spice that gives curry its yellow color", a: "Turmeric", d: %w[Paprika Saffron Cinnamon], f: "Turmeric is also used as a natural dye." },
      { q: "the so-called 'king of fruits' in Southeast Asia", a: "Durian", d: %w[Mango Lychee Pineapple], f: "Famous for its strong smell." },
      { q: "the grain used in traditional Italian risotto", a: "Rice", d: %w[Wheat Barley Corn], f: "Arborio rice gives risotto its creamy texture." },
      { q: "the country famous for tacos and mole", a: "Mexico", d: %w[Peru Cuba Spain], f: "Mole is a complex sauce with many spices and often chocolate." },
      { q: "the country where pasta is the staple national dish", a: "Italy", d: %w[Greece Spain Portugal], f: "Italians eat over 50 lb of pasta per person per year." },
      { q: "the cheese named after an Italian region", a: "Parmesan", d: %w[Cheddar Brie Gouda], f: "Parmigiano-Reggiano comes from Parma, Italy." },
      { q: "the country where ceviche is a national dish", a: "Peru", d: %w[Brazil Argentina Chile], f: "Ceviche is fresh raw fish 'cooked' in citrus juice." },
      { q: "the flat Indian bread cooked in a tandoor", a: "Naan", d: %w[Roti Paratha Chapati], f: "Naan is leavened with yogurt or yeast." },
      { q: "the country that produces the most coffee", a: "Brazil", d: %w[Colombia Vietnam Ethiopia], f: "Brazil has been the top coffee producer for over 150 years." },
      { q: "the country where champagne (the wine) is from", a: "France", d: %w[Italy Spain Germany], f: "Only sparkling wine from the Champagne region can legally be called Champagne." },
      { q: "the fermented soybean paste in miso soup", a: "Miso", d: %w[Soy-sauce Tofu Wasabi], f: "Miso ferments for months to develop its flavor." },
      { q: "the tropical fruit with a tough brown husk and white flesh", a: "Coconut", d: %w[Pineapple Mango Papaya], f: "Coconuts can float across oceans to start new palms." },
      { q: "the leafy green named for an Italian city", a: "Romaine lettuce", d: %w[Spinach Kale Arugula], f: "Romaine is the lettuce of choice for Caesar salad." },
      { q: "the dough used to make croissants", a: "Laminated dough", d: [ "Pizza dough", "Sourdough", "Brioche dough" ], f: "Laminated dough is layered with butter and folded many times." },
      { q: "the Thai noodle dish with rice noodles, peanuts, and lime", a: "Pad Thai", d: [ "Tom Yum", "Massaman Curry", "Green Curry" ], f: "Pad Thai is one of Thailand's national dishes." },
      { q: "the seed used to make tahini", a: "Sesame", d: %w[Sunflower Poppy Chia], f: "Tahini is a key ingredient in hummus." },
      { q: "the South Korean spicy fermented cabbage dish", a: "Kimchi", d: %w[Tteokbokki Bibimbap Bulgogi], f: "Kimchi has hundreds of regional varieties." },
      { q: "the country where pizza margherita supposedly began", a: "Italy", d: %w[USA Greece Spain], f: "Allegedly made for Queen Margherita of Savoy in 1889 in Naples." },
      { q: "the French pastry shaped like a crescent", a: "Croissant", d: %w[Brioche Éclair Madeleine], f: "Croissants are made of laminated, butter-rich dough." },
      { q: "the rice dish from Spain with saffron and seafood or chicken", a: "Paella", d: %w[Risotto Jambalaya Biryani], f: "Paella is traditionally cooked in a wide shallow pan." },
      { q: "the Greek yogurt-and-cucumber sauce", a: "Tzatziki", d: %w[Hummus Tabbouleh Baba-ganoush], f: "Tzatziki often accompanies gyros and souvlaki." },
      { q: "the bean used to make tofu", a: "Soybean", d: %w[Chickpea Kidney-bean Mung-bean], f: "Soybeans are pressed and curdled into tofu." }
    ],
    "books" => [
      { q: "the author of the Harry Potter series", a: "J.K. Rowling", d: [ "Roald Dahl", "C.S. Lewis", "Suzanne Collins" ], f: "Rowling wrote much of book 1 in Edinburgh cafés." },
      { q: "the author of The Hobbit and The Lord of the Rings", a: "J.R.R. Tolkien", d: [ "J.K. Rowling", "C.S. Lewis", "George R.R. Martin" ], f: "Tolkien invented entire languages for Middle-earth." },
      { q: "the first book in the Chronicles of Narnia (publication order)", a: "The Lion, the Witch and the Wardrobe", d: [ "Prince Caspian", "The Magician's Nephew", "The Last Battle" ], f: "Published in 1950 by C.S. Lewis." },
      { q: "the author of Charlie and the Chocolate Factory", a: "Roald Dahl", d: [ "Eric Carle", "Beatrix Potter", "Dr. Seuss" ], f: "Dahl also wrote Matilda and James and the Giant Peach." },
      { q: "the fictional detective at 221B Baker Street", a: "Sherlock Holmes", d: [ "Hercule Poirot", "Sam Spade", "Father Brown" ], f: "Created by Sir Arthur Conan Doyle in 1887." },
      { q: "the author of '1984'", a: "George Orwell", d: [ "Aldous Huxley", "Ray Bradbury", "Margaret Atwood" ], f: "Orwell's '1984' was published in 1949." },
      { q: "the author of Pride and Prejudice", a: "Jane Austen", d: [ "Charlotte Brontë", "Emily Brontë", "Louisa May Alcott" ], f: "Pride and Prejudice was published in 1813." },
      { q: "the author of Moby-Dick", a: "Herman Melville", d: [ "Nathaniel Hawthorne", "Mark Twain", "Henry James" ], f: "Captain Ahab hunts the white whale, Moby-Dick." },
      { q: "the author of The Great Gatsby", a: "F. Scott Fitzgerald", d: [ "Ernest Hemingway", "John Steinbeck", "William Faulkner" ], f: "Published in 1925, set in the Jazz Age." },
      { q: "the author of To Kill a Mockingbird", a: "Harper Lee", d: [ "Maya Angelou", "Toni Morrison", "Eudora Welty" ], f: "Published in 1960; won the Pulitzer Prize in 1961." },
      { q: "the protagonist of The Hunger Games", a: "Katniss Everdeen", d: [ "Tris Prior", "Hermione Granger", "Bella Swan" ], f: "Katniss is from District 12." },
      { q: "the dystopian future society in The Hunger Games", a: "Panem", d: %w[Gilead Oceania Capitol], f: "Panem is divided into 12 districts." },
      { q: "the wizard mentor in The Hobbit", a: "Gandalf", d: %w[Saruman Radagast Elrond], f: "Gandalf the Grey returns as Gandalf the White in LOTR." },
      { q: "the protagonist of Don Quixote", a: "Don Quixote", d: [ "Sancho Panza", "Dulcinea", "El Cid" ], f: "Don Quixote tilts at windmills, thinking they're giants." },
      { q: "the Russian author of War and Peace", a: "Leo Tolstoy", d: %w[Dostoevsky Pushkin Chekhov], f: "War and Peace was published in 1869." },
      { q: "the protagonist of The Catcher in the Rye", a: "Holden Caulfield", d: [ "Atticus Finch", "Huck Finn", "Jay Gatsby" ], f: "Holden narrates two days of wandering New York City." },
      { q: "the children's tale about a girl who falls down a rabbit hole", a: "Alice's Adventures in Wonderland", d: [ "Through the Looking-Glass", "The Wizard of Oz", "Peter Pan" ], f: "By Lewis Carroll, published in 1865." },
      { q: "the author of The Old Man and the Sea", a: "Ernest Hemingway", d: [ "John Steinbeck", "Cormac McCarthy", "Jack London" ], f: "It won Hemingway the 1953 Pulitzer." },
      { q: "the author of A Brief History of Time", a: "Stephen Hawking", d: [ "Carl Sagan", "Brian Greene", "Neil deGrasse Tyson" ], f: "Hawking's 1988 book popularized cosmology." },
      { q: "the central artifact in The Lord of the Rings", a: "The One Ring", d: [ "Excalibur", "Mjolnir", "The Holy Grail" ], f: "Frodo must destroy the Ring in Mount Doom." },
      { q: "the author of The Grapes of Wrath", a: "John Steinbeck", d: [ "William Faulkner", "Ernest Hemingway", "F. Scott Fitzgerald" ], f: "Steinbeck won the Pulitzer for it in 1940." },
      { q: "the author of the Discworld series", a: "Terry Pratchett", d: [ "Douglas Adams", "Neil Gaiman", "Brandon Sanderson" ], f: "Discworld is a flat disc on the back of a turtle." },
      { q: "the children's classic featuring a stuffed bear and a small boy", a: "Winnie-the-Pooh", d: [ "Paddington", "Corduroy", "The Velveteen Rabbit" ], f: "A.A. Milne wrote it in 1926." },
      { q: "the genre of Frank Herbert's Dune", a: "Science fiction", d: %w[Fantasy Mystery Romance], f: "Dune is set on the desert planet Arrakis." },
      { q: "the protagonist of The Book Thief", a: "Liesel Meminger", d: %w[Anne-Frank Sophie-Scholl Hanna-Schmitz], f: "Liesel steals books in Nazi Germany." }
    ],
    "photography" => [
      { q: "what ISO controls on a camera", a: "Sensor sensitivity to light", d: [ "Color balance", "Shutter speed", "Lens aperture" ], f: "Higher ISO = brighter photo, but more grain." },
      { q: "what's measured in f-stops on a camera lens", a: "Aperture", d: %w[Zoom Shutter ISO], f: "f/1.8 is a wider opening than f/16." },
      { q: "the setting that controls how long light hits the sensor", a: "Shutter speed", d: %w[ISO Aperture White-balance], f: "Slow shutter = motion blur; fast shutter freezes action." },
      { q: "the photography composition guideline that divides the frame into 3×3", a: "Rule of thirds", d: [ "Golden ratio", "Symmetry", "Triangle balance" ], f: "Place key subjects along the grid lines or intersections." },
      { q: "what HDR stands for in photography", a: "High Dynamic Range", d: [ "High Definition Render", "Hyper Depth Resolution", "Hue Detail Reset" ], f: "HDR blends multiple exposures to keep shadows and highlights visible." },
      { q: "a lens type with a very wide field of view", a: "Wide-angle lens", d: [ "Telephoto lens", "Macro lens", "Fisheye-only lens" ], f: "Wide-angle lenses (e.g. 24mm) capture more of a scene." },
      { q: "the trinity of exposure", a: "Aperture, shutter speed, ISO", d: [ "Color, contrast, sharpness", "Hue, saturation, brightness", "Focus, zoom, ISO" ], f: "All three together control the brightness of the photo." },
      { q: "the light at the start and end of the day", a: "Golden hour", d: [ "Blue hour", "Magic hour", "Bracket hour" ], f: "Golden hour produces warm, soft, directional light." },
      { q: "the dim, blue-tinted light just before sunrise or just after sunset", a: "Blue hour", d: [ "Golden hour", "Twilight zone", "Magic hour" ], f: "Blue hour is favored for cityscape shots." },
      { q: "a lens that magnifies very small subjects close-up", a: "Macro lens", d: %w[Wide-angle Telephoto Tilt-shift], f: "Macro lenses can achieve 1:1 magnification." },
      { q: "the term for a photograph of yourself", a: "Selfie", d: %w[Portrait Self-portrait Headshot], f: "Selfies are usually taken with a smartphone." },
      { q: "the studio backdrop color easily removed in post-processing", a: "Green", d: %w[Blue Red White], f: "Green screens are common for compositing." },
      { q: "the slight motion blur a tripod helps prevent", a: "Camera shake", d: %w[Subject-motion Lens-flare Vignetting], f: "Tripods stabilize the camera for long exposures." },
      { q: "the term for the artistic blur of out-of-focus background", a: "Bokeh", d: %w[Glare Soft-focus Diffraction], f: "Bokeh quality depends on lens aperture shape and aperture size." },
      { q: "the file format that preserves raw sensor data", a: "RAW", d: %w[JPEG PNG TIFF], f: "RAW files keep more information for editing than JPEG." },
      { q: "the technique of taking a long-exposure of star trails", a: "Astrophotography", d: %w[Street-photography Sports-photography Portraiture], f: "Stars 'trail' as Earth rotates." },
      { q: "the part of the camera that captures the image", a: "Sensor", d: %w[Lens Mirror Viewfinder], f: "Modern sensors are CMOS or CCD." },
      { q: "the term for a camera with a fixed lens and pop-up flash", a: "Point-and-shoot", d: [ "DSLR", "Mirrorless", "Medium format" ], f: "Point-and-shoots are compact but typically have small sensors." },
      { q: "the photography software made by Adobe for editing", a: "Lightroom", d: %w[Photoshop InDesign Illustrator], f: "Lightroom focuses on RAW workflow and color grading." },
      { q: "the photographer famous for landscapes of Yosemite (Ansel ___)", a: "Adams", d: %w[Smith Ross Lewis], f: "Ansel Adams pioneered the Zone System for exposure." },
      { q: "the standard professional aspect ratio for a portrait print", a: "4:5", d: %w[3:2 16:9 1:1], f: "4:5 is common for portrait prints and magazine covers." },
      { q: "a camera technique that emphasizes light streaks during long exposures", a: "Light painting", d: %w[Time-lapse Tilt-shift Panning], f: "Light painting uses a flashlight or other source during a long exposure." },
      { q: "the camera setting that adjusts color accuracy", a: "White balance", d: %w[ISO Aperture Shutter-speed], f: "White balance compensates for the color of the light source." },
      { q: "the modular hot-shoe-mounted flash unit", a: "Speedlight", d: %w[Reflector Softbox Ringlight], f: "Speedlights provide portable, off-camera flash." },
      { q: "the brand that pioneered instant film cameras", a: "Polaroid", d: %w[Kodak Fujifilm Canon], f: "Polaroid's first instant camera was released in 1948." }
    ],
    "gardening" => [
      { q: "what bees collect from flowers", a: "Nectar and pollen", d: %w[Honey Petals Leaves], f: "Bees make honey from nectar." },
      { q: "the process plants use to make food from sunlight", a: "Photosynthesis", d: %w[Respiration Germination Pollination], f: "CO₂ + water + sunlight → sugar + oxygen." },
      { q: "the part of a plant that anchors it and absorbs water", a: "Root", d: %w[Stem Leaf Flower], f: "Roots also pull dissolved nutrients from the soil." },
      { q: "the pH level of neutral soil", a: "7", d: %w[5 6 8], f: "Below 7 is acidic; above 7 is alkaline." },
      { q: "the practice of planting different crops in the same plot over time", a: "Crop rotation", d: %w[Mulching Composting Pollination], f: "Rotating crops keeps soil healthy and reduces pests." },
      { q: "the pollinating insect with colorful wings", a: "Butterfly", d: %w[Wasp Mosquito Termite], f: "Butterflies are major flower visitors." },
      { q: "the material used to suppress weeds and retain moisture around plants", a: "Mulch", d: %w[Fertilizer Pesticide Compost], f: "Wood chips, straw, and bark are common mulches." },
      { q: "the process of starting a plant from a seed sprouting", a: "Germination", d: %w[Pollination Photosynthesis Transpiration], f: "Germination requires water, warmth, and oxygen." },
      { q: "the macronutrient most important for leafy growth", a: "Nitrogen", d: %w[Phosphorus Potassium Sulfur], f: "Symbolized N in the N-P-K fertilizer rating." },
      { q: "the type of fertilizer made from kitchen and yard scraps", a: "Compost", d: %w[Manure Bone-meal Synthetic-fertilizer], f: "Composting recycles food and plant waste into soil amendment." },
      { q: "the season most vegetables are planted in temperate climates", a: "Spring", d: %w[Summer Fall Winter], f: "Last-frost dates dictate when to plant." },
      { q: "the practice of growing many plants in pots, often on balconies", a: "Container gardening", d: [ "Hydroponics", "Vertical gardening", "Aquaponics" ], f: "Container gardening lets people grow plants in small spaces." },
      { q: "the system that grows plants without soil, using nutrient water", a: "Hydroponics", d: %w[Aquaponics Aeroponics Permaculture], f: "Hydroponic plants get nutrients directly from a water solution." },
      { q: "the term for plants that live for many years", a: "Perennial", d: %w[Annual Biennial Bulb], f: "Perennials regrow each year." },
      { q: "the term for plants that complete their life cycle in one year", a: "Annual", d: %w[Perennial Biennial Evergreen], f: "Tomatoes, basil, and marigolds are annuals in most climates." },
      { q: "the plant family that includes tomatoes, peppers, and potatoes", a: "Nightshade", d: %w[Brassica Allium Cucurbit], f: "Nightshades are also called Solanaceae." },
      { q: "the plant family that includes broccoli, kale, and cabbage", a: "Brassica", d: %w[Nightshade Allium Cucurbit], f: "Brassicas are also called cruciferous vegetables." },
      { q: "the plant family that includes cucumbers, squash, and pumpkins", a: "Cucurbit", d: %w[Nightshade Brassica Allium], f: "Cucurbits often have sprawling vines." },
      { q: "the gardening technique of pruning to encourage branching", a: "Pinching", d: %w[Topping Deadheading Layering], f: "Pinching back the tip makes a plant grow bushier." },
      { q: "the term for removing spent flowers to encourage more blooms", a: "Deadheading", d: %w[Pinching Topping Pruning], f: "Deadheading directs energy to new flowers rather than seed production." },
      { q: "the term for soil mixed with compost and other organic matter", a: "Amended soil", d: [ "Topsoil", "Subsoil", "Sand" ], f: "Amending improves drainage and nutrient content." },
      { q: "the herb known for its strong licorice-anise scent", a: "Basil", d: %w[Rosemary Sage Thyme], f: "Basil is the star of pesto." },
      { q: "the part of a flower that produces pollen", a: "Stamen", d: %w[Pistil Sepal Stigma], f: "Stamens are the male parts of the flower." },
      { q: "the part of a flower that receives pollen", a: "Stigma", d: %w[Stamen Petal Calyx], f: "Stigmas sit on top of the pistil." },
      { q: "the tool used to break up compacted soil", a: "Tiller", d: %w[Trowel Rake Spade], f: "Tilling aerates soil and incorporates amendments." }
    ],
    "art" => [
      { q: "the painter of the Mona Lisa", a: "Leonardo da Vinci", d: %w[Picasso Van-Gogh Michelangelo], f: "Leonardo started it around 1503 and never quite 'finished'." },
      { q: "the painter of the Sistine Chapel ceiling", a: "Michelangelo", d: %w[Raphael Donatello Leonardo-da-Vinci], f: "It took him about four years (1508–1512)." },
      { q: "the artist who cut off part of his own ear", a: "Vincent van Gogh", d: %w[Picasso Monet Dalí], f: "After a fight with Paul Gauguin in 1888." },
      { q: "the movement most associated with Claude Monet", a: "Impressionism", d: %w[Cubism Surrealism Pop-art], f: "The term came from Monet's painting 'Impression, Sunrise'." },
      { q: "the artist of 'The Scream'", a: "Edvard Munch", d: [ "Vincent van Gogh", "Salvador Dalí", "Pablo Picasso" ], f: "Munch painted multiple versions between 1893 and 1910." },
      { q: "the term for an artist's painting of themselves", a: "Self-portrait", d: %w[Still-life Landscape Mural], f: "Van Gogh painted dozens of his own self-portraits." },
      { q: "the medium of pencil drawing on paper", a: "Graphite", d: %w[Charcoal Pastel Ink], f: "Graphite hardness varies from 9H (hard) to 9B (soft)." },
      { q: "the art movement of Picasso and Braque featuring fragmented forms", a: "Cubism", d: %w[Surrealism Futurism Expressionism], f: "Cubism began around 1907 in Paris." },
      { q: "the artist of 'The Persistence of Memory' (with melting clocks)", a: "Salvador Dalí", d: %w[Magritte Picasso Miró], f: "A surrealist painting from 1931." },
      { q: "the painter known for grand-scale baroque ceiling frescos at Versailles", a: "Charles Le Brun", d: [ "Jacques-Louis David", "Jean-Honoré Fragonard", "Antoine Watteau" ], f: "Le Brun directed art at Louis XIV's court." },
      { q: "the medium of 'David', Michelangelo's famous sculpture", a: "Marble", d: %w[Bronze Wood Granite], f: "The 17-foot statue was completed in 1504." },
      { q: "the term for a painting done directly on fresh wet plaster", a: "Fresco", d: %w[Mural Tempera Encaustic], f: "Michelangelo painted the Sistine Chapel ceiling as a fresco." },
      { q: "the artist born Pablo Diego José Francisco de Paula Juan Nepomuceno Ruiz y Picasso", a: "Pablo Picasso", d: %w[Salvador-Dalí Joan-Miró Diego-Rivera], f: "Picasso went through multiple distinct artistic 'periods'." },
      { q: "the Dutch master known for 'The Night Watch'", a: "Rembrandt", d: %w[Vermeer Van-Gogh Hals], f: "Rembrandt completed The Night Watch in 1642." },
      { q: "the painter of 'Girl with a Pearl Earring'", a: "Johannes Vermeer", d: %w[Rembrandt Hals Van-Eyck], f: "Painted around 1665." },
      { q: "the artist behind 'American Gothic' (the farmer-and-daughter painting)", a: "Grant Wood", d: [ "Norman Rockwell", "Edward Hopper", "Andrew Wyeth" ], f: "Painted in 1930 in Iowa." },
      { q: "the term for art created via stencils and spray paint on public walls", a: "Street art", d: %w[Graffiti Mosaic Decoupage], f: "Banksy is a famous street artist." },
      { q: "the period featuring artists like Donatello and Botticelli in Italy", a: "Renaissance", d: [ "Baroque", "Rococo", "Mannerism" ], f: "The Italian Renaissance flourished from the 14th to 17th centuries." },
      { q: "the Mexican painter married to Diego Rivera and famous for her self-portraits", a: "Frida Kahlo", d: [ "Georgia O'Keeffe", "Tamara de Lempicka", "Mary Cassatt" ], f: "Kahlo painted with vivid imagery rooted in Mexican folk art." },
      { q: "the art movement known for dripping paint and abstract forms (Jackson Pollock)", a: "Abstract expressionism", d: %w[Pop-art Minimalism Realism], f: "Pollock's drip paintings became icons of postwar American art." },
      { q: "the term for sculpture carved from a single piece of stone", a: "Monolithic", d: [ "Cast", "Assemblage", "Bas-relief" ], f: "Monolithic sculptures are carved 'in one piece'." },
      { q: "the artist of the 1907 Cubist work 'Les Demoiselles d'Avignon'", a: "Pablo Picasso", d: [ "Henri Matisse", "Georges Braque", "Marc Chagall" ], f: "It's considered a milestone in early modern art." },
      { q: "the term for an image made of small colored tiles", a: "Mosaic", d: %w[Collage Mural Diorama], f: "Mosaics date back thousands of years." },
      { q: "the Pop artist famous for Campbell's soup can paintings", a: "Andy Warhol", d: [ "Roy Lichtenstein", "Jasper Johns", "Robert Rauschenberg" ], f: "Warhol's silkscreens made everyday products into art." },
      { q: "the artist who painted 'Starry Night'", a: "Vincent van Gogh", d: [ "Claude Monet", "Edvard Munch", "Pierre-Auguste Renoir" ], f: "Painted in 1889 while at the Saint-Rémy asylum." }
    ],
    "cooking" => [
      { q: "the Celsius temperature at which water freezes", a: "0°C", d: [ "-10°C", "10°C", "32°C" ], f: "0°C = 32°F." },
      { q: "the cooking method that submerges food in hot oil", a: "Frying", d: %w[Boiling Steaming Grilling], f: "Frying makes food crisp because oil reaches much higher temps than water." },
      { q: "what 'al dente' means for pasta", a: "Firm to the bite", d: [ "Very soft", "Cooked with cheese", "Served cold" ], f: "Italian for 'to the tooth'." },
      { q: "the leavening agent in most breads", a: "Yeast", d: %w[Salt Sugar Butter], f: "Yeast eats sugar and releases CO₂, making dough rise." },
      { q: "the safe internal temperature (°F) for cooked chicken", a: "165°F", d: %w[145°F 155°F 185°F], f: "165°F kills harmful bacteria like salmonella." },
      { q: "the cooking method that uses dry heat in an enclosed space", a: "Roasting", d: %w[Boiling Poaching Steaming], f: "Ovens roast or bake with circulating hot air." },
      { q: "the cooking method that simmers food in liquid below boiling", a: "Poaching", d: %w[Sautéing Searing Braising], f: "Poached eggs are cooked in water below 200°F." },
      { q: "the technique of cooking food briefly in hot fat, often vegetables", a: "Sautéing", d: %w[Braising Roasting Poaching], f: "Sauté means 'to jump' in French — referring to tossing in the pan." },
      { q: "the method that cooks low and slow in a covered pot with liquid", a: "Braising", d: %w[Frying Grilling Boiling], f: "Braising is great for tough cuts of meat." },
      { q: "the fat used in classic Indian cooking, similar to clarified butter", a: "Ghee", d: %w[Olive-oil Lard Sesame-oil], f: "Ghee has a high smoke point and a nutty flavor." },
      { q: "the herb most commonly used in pesto", a: "Basil", d: %w[Parsley Cilantro Mint], f: "Genovese basil is the classic pesto herb." },
      { q: "the kitchen tool used to whisk eggs", a: "Whisk", d: %w[Spatula Tongs Slotted-spoon], f: "Balloon whisks are best for incorporating air into eggs." },
      { q: "the term for tomatoes peeled and chopped quickly with hot-water shock", a: "Blanching", d: %w[Braising Searing Roasting], f: "Blanching loosens the skin and stops enzyme activity." },
      { q: "the temperature at which butter starts to smoke", a: "About 350°F", d: %w[200°F 250°F 400°F], f: "Smoke point of butter is roughly 350°F (177°C)." },
      { q: "the French sauce mother that includes hollandaise and béarnaise", a: "Emulsion (Hollandaise)", d: [ "Béchamel", "Velouté", "Espagnole" ], f: "There are five 'mother sauces' in French cuisine." },
      { q: "the technique of using a fan-assisted oven", a: "Convection", d: %w[Conduction Radiation Induction], f: "Convection ovens circulate hot air for even cooking." },
      { q: "the cooking style featuring nigiri, maki, and sashimi", a: "Japanese (sushi)", d: %w[Chinese Korean Thai], f: "Sushi is one of Japan's most recognizable cuisines." },
      { q: "the bread leavened by wild yeast and lactic acid bacteria", a: "Sourdough", d: %w[Brioche Challah Ciabatta], f: "Sourdough starter is a culture of yeast and bacteria." },
      { q: "the term for cutting food into very small uniform cubes", a: "Brunoise", d: %w[Julienne Chiffonade Mince], f: "Brunoise is ~3mm cubes." },
      { q: "the term for stacking and rolling herbs to ribbon-cut them", a: "Chiffonade", d: %w[Julienne Brunoise Mince], f: "Chiffonade is great for basil and mint." },
      { q: "the term for thin matchstick cuts of vegetables", a: "Julienne", d: %w[Brunoise Mince Cube], f: "Julienne carrots are about 3mm × 3mm × 5cm." },
      { q: "the ingredient that browns proteins via the Maillard reaction", a: "Heat (high)", d: %w[Acid Salt Sugar], f: "The Maillard reaction occurs above ~280°F (140°C)." },
      { q: "the method of cooking food slowly in fat", a: "Confit", d: %w[Sous-vide Braising Smoking], f: "Duck confit is a classic French preparation." },
      { q: "the precise water-bath cooking technique using vacuum-sealed bags", a: "Sous-vide", d: %w[Confit Braising Steaming], f: "Sous-vide cooks at exact temperatures for hours." },
      { q: "the method of preserving food with smoke", a: "Smoking", d: %w[Curing Pickling Fermenting], f: "Smoking imparts flavor and helps preserve meats and fish." }
    ],
    "travel" => [
      { q: "the city of the Eiffel Tower", a: "Paris", d: %w[London Rome Madrid], f: "Built for the 1889 World's Fair." },
      { q: "the approximate height of the Eiffel Tower to its tip", a: "1,083 ft", d: [ "330 ft", "550 ft", "2,000 ft" ], f: "About 330 m — once the tallest structure in the world." },
      { q: "the city of the Colosseum", a: "Rome", d: %w[Athens Florence Naples], f: "Completed in 80 AD; held up to 80,000 spectators." },
      { q: "the country of Machu Picchu", a: "Peru", d: %w[Mexico Chile Brazil], f: "Built by the Inca around 1450 high in the Andes." },
      { q: "the country that gifted the Statue of Liberty to the US", a: "France", d: %w[Spain Italy England], f: "France gifted it to the US in 1886." },
      { q: "the waterfall on the border of US and Canada", a: "Niagara Falls", d: [ "Victoria Falls", "Angel Falls", "Iguazu Falls" ], f: "About 6 million cubic feet of water per minute go over Horseshoe Falls." },
      { q: "the city of Times Square", a: "New York City", d: %w[Chicago Los-Angeles Las-Vegas], f: "Times Square draws over 50 million visitors per year." },
      { q: "the country of Petra, the rose-red ancient city", a: "Jordan", d: %w[Egypt Lebanon Syria], f: "Petra was rediscovered by Europeans in 1812." },
      { q: "the city of Big Ben", a: "London", d: %w[Manchester Edinburgh Dublin], f: "Big Ben is technically the name of the bell inside the tower." },
      { q: "the city of the Sydney Opera House", a: "Sydney", d: %w[Melbourne Brisbane Perth], f: "Opened in 1973; designed by Jørn Utzon." },
      { q: "the city of the Acropolis", a: "Athens", d: %w[Rome Cairo Istanbul], f: "The Parthenon sits atop the Acropolis." },
      { q: "the city of the Great Wall of China's most-visited section (Badaling)", a: "Beijing", d: %w[Shanghai Xi'an Chengdu], f: "Badaling is about 70 km northwest of Beijing." },
      { q: "the country of the Grand Canyon", a: "United States", d: %w[Mexico Canada Argentina], f: "Carved by the Colorado River over millions of years." },
      { q: "the city of the Burj Khalifa", a: "Dubai", d: %w[Abu-Dhabi Doha Riyadh], f: "At 828 m, the Burj Khalifa is the world's tallest building." },
      { q: "the lake known as 'the Pearl of Siberia'", a: "Lake Baikal", d: [ "Lake Tahoe", "Lake Como", "Lake Victoria" ], f: "Baikal is the world's deepest and oldest freshwater lake." },
      { q: "the city of the Taj Mahal", a: "Agra", d: %w[Delhi Jaipur Mumbai], f: "Built between 1632 and 1653 by Shah Jahan." },
      { q: "the country of the pyramids of Giza", a: "Egypt", d: %w[Mexico Sudan Iraq], f: "Built around 2560 BC for Pharaoh Khufu." },
      { q: "the country of the Northern Lights' famous viewing spots like Tromsø", a: "Norway", d: %w[Sweden Finland Iceland], f: "Tromsø sits within the Arctic Circle." },
      { q: "the country of the Eiffel-Tower-like Tokyo Tower", a: "Japan", d: [ "China", "South Korea", "Indonesia" ], f: "Tokyo Tower was completed in 1958." },
      { q: "the country of the Great Barrier Reef", a: "Australia", d: [ "Indonesia", "Philippines", "Papua New Guinea" ], f: "It's the world's largest coral reef system." },
      { q: "the country of Iguazu Falls (its larger share)", a: "Argentina", d: %w[Brazil Uruguay Paraguay], f: "Iguazu Falls span the Argentina-Brazil border, with Argentina hosting more." },
      { q: "the world's largest hot desert", a: "Sahara", d: [ "Gobi", "Arabian", "Kalahari" ], f: "The Sahara covers most of North Africa." },
      { q: "the country of the Cliffs of Moher", a: "Ireland", d: %w[Scotland Wales Iceland], f: "The cliffs rise up to 214 m above the Atlantic." },
      { q: "the airline whose hub is Singapore Changi Airport", a: "Singapore Airlines", d: %w[Cathay-Pacific Qantas Emirates], f: "Changi has been voted world's best airport multiple times." },
      { q: "the country of Mount Kilimanjaro", a: "Tanzania", d: %w[Kenya Uganda Ethiopia], f: "Kilimanjaro is the highest peak in Africa at 5,895 m." }
    ]
  }.freeze

  # Builds a unique context phrase per (category, variant) so chain intros stay
  # distinguishable across thousands of chains in one tag.
  def self.flavor_for(category, variant_index)
    flavor = FLAVORS[variant_index % FLAVORS.size]
    suffix = variant_index >= FLAVORS.size ? " ##{variant_index + 1}" : ""
    "#{category.humanize} · #{flavor}#{suffix}"
  end

  # Returns an array of chain hashes shaped for the bulk seeder:
  #   { tag:, difficulty:, intro:, steps: [{q:, options:, answer:, fun_fact:}, ...] }
  def self.generate(category, target_count: 1000, steps_per_chain: 6)
    facts = FACTS[category]
    return [] unless facts && facts.size >= steps_per_chain

    chains_needed = (target_count.to_f / steps_per_chain).ceil
    chains_needed.times.map do |vi|
      rng = Random.new(("#{category}-#{vi}").hash & 0x7fffffff)
      chain_facts = facts.sample(steps_per_chain, random: rng)
      flavor = flavor_for(category, vi)
      {
        tag: category,
        difficulty: %w[easy medium].sample(random: rng),
        intro: "Quick #{category.humanize.downcase} tour · #{flavor}",
        steps: chain_facts.map { |f| step_for(f, rng) }
      }
    end
  end

  def self.step_for(fact, rng)
    options = ([ fact[:a] ] + fact[:d]).shuffle(random: rng)
    {
      q: "Which is #{fact[:q]}?",
      options: options,
      answer: options.index(fact[:a]),
      fun_fact: fact[:f]
    }
  end

  def self.categories
    FACTS.keys
  end
end
